version: "3.5"

services:
  db:
    container_name: db
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
    - postgres-data:/var/lib/postgresql/data/
    env_file:
      - ./docker/postgres/.env


  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./app:/usr/src/app
      - static-files:/usr/src/app/static
      - media-files:/usr/src/app/media
    env_file:
      - ./docker/app/.env
    depends_on:
      - db


  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
       - 8080:80
    volumes:
      - static-files:/habr/static
      - media-files:/habr/media
    depends_on:
      - app


volumes:
  postgres-data:
  static-files:
  media-files:
